# Quantum-Vulnerable Cryptography Detection Benchmark Configuration

# LLM API Configuration
# API keys are loaded from environment variables (.env file)
llm_providers:
  openai:
    api_key_env: "OPENAI_API_KEY"
    model_env: "OPENAI_MODEL"
    base_url_env: "OPENAI_BASE_URL"

  google:
    api_key_env: "GOOGLE_API_KEY"
    model_env: "GOOGLE_MODEL"
    base_url_env: "GOOGLE_BASE_URL"

  anthropic:
    api_key_env: "ANTHROPIC_API_KEY"
    model_env: "ANTHROPIC_MODEL"
    base_url_env: "ANTHROPIC_BASE_URL"

  xai:
    api_key_env: "XAI_API_KEY"
    model_env: "XAI_MODEL"
    base_url_env: "XAI_BASE_URL"

  ollama:
    api_key: "not_required"
    model_env: "OLLAMA_MODEL"
    base_url_env: "OLLAMA_BASE_URL"
    # 또는 직접 여러 모델 지정 (환경 변수 대신)
    # model: ["llama3:8b", "qwen3:8b", "codellama:7b"]
    # base_url: "http://localhost:11434"

  local_ai:
    api_key_env: "LOCAL_AI_API_KEY"
    model_env: "LOCAL_AI_MODEL"
    base_url_env: "LOCAL_AI_BASE_URL"

# Analysis Agents Configuration for Quantum-Vulnerable Algorithm Detection
agents:
  source_code:
    name: "Source Code Vulnerable Crypto Detection Agent"
    description: "Analyzes source code to detect quantum-vulnerable cryptographic algorithms including Korean domestic algorithms"
    prompt_template: "You are an expert in cryptography and quantum vulnerability assessment. Analyze the following source code and identify: {analysis_points}. Focus on detecting classical cryptographic algorithms that are vulnerable to quantum attacks, including RSA, ECC, DH, DSA, Korean algorithms like SEED, ARIA, HIGHT, LEA, and other algorithms vulnerable to Shor's and Grover's algorithms. Look for both obvious implementations and obfuscated/indirect usage patterns that simple pattern matching cannot detect."

  assembly_binary:
    name: "Assembly Binary Vulnerable Crypto Detection Agent"
    description: "Analyzes compiled assembly/binary code to detect quantum-vulnerable cryptographic operations including Korean algorithms"
    prompt_template: "You are an expert in cryptography and assembly analysis. Examine the following assembly/binary code and detect: {analysis_points}. Look for signatures of quantum-vulnerable crypto algorithms, including RSA operations, elliptic curve arithmetic, discrete logarithm computations, Korean cipher implementations (SEED, ARIA, HIGHT, LEA), and other quantum-vulnerable mathematical operations in compiled code that pattern matching might miss."

  logs_config:
    name: "Configuration and Logs Vulnerable Crypto Analysis Agent"
    description: "Analyzes configuration files and logs to detect quantum-vulnerable cryptography settings including Korean algorithms"
    prompt_template: "You are an expert in cryptography configuration and logging. Examine the following logs/configuration data and determine: {analysis_points}. Look for quantum-vulnerable crypto algorithm references, vulnerable cipher suites, RSA/ECC certificates, Korean algorithm configurations, and indicators of quantum-vulnerable cryptographic setups that simple string matching cannot identify."

# Benchmark Configuration
benchmark:
  timeout_seconds: 45
  max_retries: 3
  metrics:
    - vulnerable_crypto_detection_accuracy
    - algorithm_identification_precision
    - false_positive_rate
    - false_negative_rate
    - response_time
    - json_validity
    - completeness

  test_cases_per_agent: 20
  output_format: "csv"

  # Quantum-vulnerable algorithms categorized by attack type
  vulnerable_algorithms:
    shor_vulnerable:
      public_key_crypto: ["RSA", "ECC", "ECDSA", "ECDH", "DSA", "DH", "ElGamal"]
      korean_public_key: ["KCDSA", "EC-KCDSA"]

    grover_vulnerable:
      symmetric_ciphers: ["AES-128", "3DES", "DES", "RC4", "Blowfish", "Twofish"]
      korean_symmetric: ["SEED", "ARIA-128", "HIGHT", "LEA-128"]
      hash_functions: ["SHA-1", "SHA-256", "MD5", "MD4", "SHA-224"]
      korean_hash: ["HAS-160", "LSH-256"]

    other_vulnerable:
      stream_ciphers: ["RC4", "A5/1", "A5/2", "E0"]
      block_ciphers_weak: ["DES", "3DES", "RC5", "RC6"]
      korean_legacy: ["SEED-128", "old-ARIA", "HIGHT-64"]
      mac_algorithms: ["HMAC-MD5", "HMAC-SHA1"]

    implementation_vulnerable:
      padding_schemes: ["PKCS#1 v1.5", "OAEP-SHA1"]
      random_generators: ["Linear Congruential", "Mersenne Twister"]
      key_derivation: ["PBKDF1", "weak KDF"]

# Paths
paths:
  test_cases: "data/test_cases"
  test_files: "data/test_files"
  ground_truth: "data/ground_truth"
  results: "results"